/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AssurancesRouteImport } from './routes/assurances'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvocatsRouteImport } from './routes/avocats'
import { Route as BibliothequeRouteImport } from './routes/bibliotheque'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as CabinetsRouteImport } from './routes/cabinets'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisciplineRouteImport } from './routes/discipline'
import { Route as EspaceAvocatRouteImport } from './routes/espace-avocat'
import { Route as EspaceBatonnierRouteImport } from './routes/espace-batonnier'
import { Route as ExamenRouteImport } from './routes/examen'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as LeBarreauRouteImport } from './routes/le-barreau'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as PortailClientRouteImport } from './routes/portail-client'
import { Route as PortailClientInscriptionRouteImport } from './routes/portail-client-inscription'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignalementRouteImport } from './routes/signalement'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedExaminateurRouteImport } from './routes/_authenticated/examinateur'
import { Route as AuthenticatedFormateurRouteImport } from './routes/_authenticated/formateur'
import { Route as AuthenticatedMesDossiersDisciplinairesRouteImport } from './routes/_authenticated/mes-dossiers-disciplinaires'
import { Route as AuthenticatedMessagerieRouteImport } from './routes/_authenticated/messagerie'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedTachesRouteImport } from './routes/_authenticated/taches'
import { Route as ApiDbRouteImport } from './routes/api/db'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AvocatsIdRouteImport } from './routes/avocats.$id'
import { Route as PortailClientIndexRouteImport } from './routes/portail-client.index'
import { Route as PortailClientAuthRouteImport } from './routes/portail-client.auth'
import { Route as PortailClientDocumentsRouteImport } from './routes/portail-client.documents'
import { Route as PortailClientDossiersRouteImport } from './routes/portail-client.dossiers'
import { Route as PortailClientMessagesRouteImport } from './routes/portail-client.messages'
import { Route as PortailClientNotificationsRouteImport } from './routes/portail-client.notifications'
import { Route as PortailClientSignaturesRouteImport } from './routes/portail-client.signatures'
import { Route as SignatureTokenRouteImport } from './routes/signature.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActualitesRouteImport } from './routes/_authenticated/admin.actualites'
import { Route as AuthenticatedAdminAvocatsRouteImport } from './routes/_authenticated/admin.avocats'
import { Route as AuthenticatedAdminBibliothequeRouteImport } from './routes/_authenticated/admin.bibliotheque'
import { Route as AuthenticatedAdminCabinetsRouteImport } from './routes/_authenticated/admin.cabinets'
import { Route as AuthenticatedAdminContenusRouteImport } from './routes/_authenticated/admin.contenus'
import { Route as AuthenticatedAdminDemandesRouteImport } from './routes/_authenticated/admin.demandes'
import { Route as AuthenticatedAdminDisciplineRouteImport } from './routes/_authenticated/admin.discipline'
import { Route as AuthenticatedAdminEnterprisesRouteImport } from './routes/_authenticated/admin.enterprises'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin.journal'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminSauvegardesRouteImport } from './routes/_authenticated/admin.sauvegardes'
import { Route as AuthenticatedCabinetIndexRouteImport } from './routes/_authenticated/cabinet.index'
import { Route as AuthenticatedCabinetDossiersRouteImport } from './routes/_authenticated/cabinet.dossiers'
import { Route as AuthenticatedCabinetFacturationRouteImport } from './routes/_authenticated/cabinet.facturation'
import { Route as AuthenticatedCabinetFormationsRouteImport } from './routes/_authenticated/cabinet.formations'
import { Route as AuthenticatedCabinetMembresRouteImport } from './routes/_authenticated/cabinet.membres'
import { Route as AuthenticatedCabinetModelesRouteImport } from './routes/_authenticated/cabinet.modeles'
import { Route as AuthenticatedCabinetParametresRouteImport } from './routes/_authenticated/cabinet.parametres'
import { Route as AuthenticatedCabinetTarifsRouteImport } from './routes/_authenticated/cabinet.tarifs'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedDossiersIndexRouteImport } from './routes/_authenticated/dossiers.index'
import { Route as AuthenticatedDossiersMatterIdRouteImport } from './routes/_authenticated/dossiers.$matterId'
import { Route as AuthenticatedExamensIndexRouteImport } from './routes/_authenticated/examens.index'
import { Route as AuthenticatedFacturationIndexRouteImport } from './routes/_authenticated/facturation.index'
import { Route as AuthenticatedFacturationIdRouteImport } from './routes/_authenticated/facturation.$id'
import { Route as AuthenticatedFormationsSlugRouteImport } from './routes/_authenticated/formations.$slug'
import { Route as ApiAuthActionRouteImport } from './routes/api/auth.$action'
import { Route as ApiStorageObjectRouteImport } from './routes/api/storage.object'
import { Route as ApiStorageOpRouteImport } from './routes/api/storage.op'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage.upload'
import { Route as PortailClientDossiersMatterIdRouteImport } from './routes/portail-client.dossiers.$matterId'
import { Route as VerificationFactureTokenRouteImport } from './routes/verification.facture.$token'
import { Route as AuthenticatedAdminDisciplineCaseIdRouteImport } from './routes/_authenticated/admin.discipline.$caseId'
import { Route as AuthenticatedAdminEnterprisesFirmIdRouteImport } from './routes/_authenticated/admin.enterprises.$firmId'
import { Route as AuthenticatedAdminExamensIndexRouteImport } from './routes/_authenticated/admin.examens.index'
import { Route as AuthenticatedAdminExamensIdRouteImport } from './routes/_authenticated/admin.examens.$id'
import { Route as AuthenticatedAdminFormationsIndexRouteImport } from './routes/_authenticated/admin.formations.index'
import { Route as AuthenticatedAdminFormationsIdRouteImport } from './routes/_authenticated/admin.formations.$id'
import { Route as AuthenticatedExamensIdPassageRouteImport } from './routes/_authenticated/examens.$id.passage'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth.discord.callback'
import { Route as ApiAuthDiscordOnboardingRouteImport } from './routes/api/auth.discord.onboarding'
import { Route as ApiAuthDiscordStartRouteImport } from './routes/api/auth.discord.start'
import { Route as AuthenticatedExamensIdResultatAttemptIdRouteImport } from './routes/_authenticated/examens.$id.resultat.$attemptId'
import { Route as AuthenticatedAdminExamensIdCopiesAttemptIdRouteImport } from './routes/_authenticated/admin.examens.$id.copies.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AssurancesRoute = AssurancesRouteImport.update({
  id: '/assurances',
  path: '/assurances',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvocatsRoute = AvocatsRouteImport.update({
  id: '/avocats',
  path: '/avocats',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetsRoute = CabinetsRouteImport.update({
  id: '/cabinets',
  path: '/cabinets',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceAvocatRoute = EspaceAvocatRouteImport.update({
  id: '/espace-avocat',
  path: '/espace-avocat',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceBatonnierRoute = EspaceBatonnierRouteImport.update({
  id: '/espace-batonnier',
  path: '/espace-batonnier',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenRoute = ExamenRouteImport.update({
  id: '/examen',
  path: '/examen',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const LeBarreauRoute = LeBarreauRouteImport.update({
  id: '/le-barreau',
  path: '/le-barreau',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortailClientRoute = PortailClientRouteImport.update({
  id: '/portail-client',
  path: '/portail-client',
  getParentRoute: () => rootRouteImport,
} as any)
const PortailClientInscriptionRoute =
  PortailClientInscriptionRouteImport.update({
    id: '/portail-client-inscription',
    path: '/portail-client-inscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalementRoute = SignalementRouteImport.update({
  id: '/signalement',
  path: '/signalement',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExaminateurRoute =
  AuthenticatedExaminateurRouteImport.update({
    id: '/examinateur',
    path: '/examinateur',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormateurRoute = AuthenticatedFormateurRouteImport.update({
  id: '/formateur',
  path: '/formateur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesDossiersDisciplinairesRoute =
  AuthenticatedMesDossiersDisciplinairesRouteImport.update({
    id: '/mes-dossiers-disciplinaires',
    path: '/mes-dossiers-disciplinaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagerieRoute = AuthenticatedMessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTachesRoute = AuthenticatedTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDbRoute = ApiDbRouteImport.update({
  id: '/api/db',
  path: '/api/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AvocatsIdRoute = AvocatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AvocatsRoute,
} as any)
const PortailClientIndexRoute = PortailClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortailClientRoute,
} as any)
const PortailClientAuthRoute = PortailClientAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PortailClientRoute,
} as any)
const PortailClientDocumentsRoute = PortailClientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortailClientRoute,
} as any)
const PortailClientDossiersRoute = PortailClientDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => PortailClientRoute,
} as any)
const PortailClientMessagesRoute = PortailClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortailClientRoute,
} as any)
const PortailClientNotificationsRoute =
  PortailClientNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PortailClientRoute,
  } as any)
const PortailClientSignaturesRoute = PortailClientSignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => PortailClientRoute,
} as any)
const SignatureTokenRoute = SignatureTokenRouteImport.update({
  id: '/signature/$token',
  path: '/signature/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActualitesRoute =
  AuthenticatedAdminActualitesRouteImport.update({
    id: '/actualites',
    path: '/actualites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAvocatsRoute =
  AuthenticatedAdminAvocatsRouteImport.update({
    id: '/avocats',
    path: '/avocats',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBibliothequeRoute =
  AuthenticatedAdminBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCabinetsRoute =
  AuthenticatedAdminCabinetsRouteImport.update({
    id: '/cabinets',
    path: '/cabinets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContenusRoute =
  AuthenticatedAdminContenusRouteImport.update({
    id: '/contenus',
    path: '/contenus',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDemandesRoute =
  AuthenticatedAdminDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDisciplineRoute =
  AuthenticatedAdminDisciplineRouteImport.update({
    id: '/discipline',
    path: '/discipline',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnterprisesRoute =
  AuthenticatedAdminEnterprisesRouteImport.update({
    id: '/enterprises',
    path: '/enterprises',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSauvegardesRoute =
  AuthenticatedAdminSauvegardesRouteImport.update({
    id: '/sauvegardes',
    path: '/sauvegardes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCabinetIndexRoute =
  AuthenticatedCabinetIndexRouteImport.update({
    id: '/cabinet/',
    path: '/cabinet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetDossiersRoute =
  AuthenticatedCabinetDossiersRouteImport.update({
    id: '/cabinet/dossiers',
    path: '/cabinet/dossiers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetFacturationRoute =
  AuthenticatedCabinetFacturationRouteImport.update({
    id: '/cabinet/facturation',
    path: '/cabinet/facturation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetFormationsRoute =
  AuthenticatedCabinetFormationsRouteImport.update({
    id: '/cabinet/formations',
    path: '/cabinet/formations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetMembresRoute =
  AuthenticatedCabinetMembresRouteImport.update({
    id: '/cabinet/membres',
    path: '/cabinet/membres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetModelesRoute =
  AuthenticatedCabinetModelesRouteImport.update({
    id: '/cabinet/modeles',
    path: '/cabinet/modeles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetParametresRoute =
  AuthenticatedCabinetParametresRouteImport.update({
    id: '/cabinet/parametres',
    path: '/cabinet/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetTarifsRoute =
  AuthenticatedCabinetTarifsRouteImport.update({
    id: '/cabinet/tarifs',
    path: '/cabinet/tarifs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedDossiersIndexRoute =
  AuthenticatedDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDossiersMatterIdRoute =
  AuthenticatedDossiersMatterIdRouteImport.update({
    id: '/dossiers/$matterId',
    path: '/dossiers/$matterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamensIndexRoute =
  AuthenticatedExamensIndexRouteImport.update({
    id: '/examens/',
    path: '/examens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturationIndexRoute =
  AuthenticatedFacturationIndexRouteImport.update({
    id: '/facturation/',
    path: '/facturation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturationIdRoute =
  AuthenticatedFacturationIdRouteImport.update({
    id: '/facturation/$id',
    path: '/facturation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormationsSlugRoute =
  AuthenticatedFormationsSlugRouteImport.update({
    id: '/formations/$slug',
    path: '/formations/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthActionRoute = ApiAuthActionRouteImport.update({
  id: '/api/auth/$action',
  path: '/api/auth/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageObjectRoute = ApiStorageObjectRouteImport.update({
  id: '/api/storage/object',
  path: '/api/storage/object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageOpRoute = ApiStorageOpRouteImport.update({
  id: '/api/storage/op',
  path: '/api/storage/op',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PortailClientDossiersMatterIdRoute =
  PortailClientDossiersMatterIdRouteImport.update({
    id: '/$matterId',
    path: '/$matterId',
    getParentRoute: () => PortailClientDossiersRoute,
  } as any)
const VerificationFactureTokenRoute =
  VerificationFactureTokenRouteImport.update({
    id: '/facture/$token',
    path: '/facture/$token',
    getParentRoute: () => VerificationRoute,
  } as any)
const AuthenticatedAdminDisciplineCaseIdRoute =
  AuthenticatedAdminDisciplineCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AuthenticatedAdminDisciplineRoute,
  } as any)
const AuthenticatedAdminEnterprisesFirmIdRoute =
  AuthenticatedAdminEnterprisesFirmIdRouteImport.update({
    id: '/$firmId',
    path: '/$firmId',
    getParentRoute: () => AuthenticatedAdminEnterprisesRoute,
  } as any)
const AuthenticatedAdminExamensIndexRoute =
  AuthenticatedAdminExamensIndexRouteImport.update({
    id: '/examens/',
    path: '/examens/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamensIdRoute =
  AuthenticatedAdminExamensIdRouteImport.update({
    id: '/examens/$id',
    path: '/examens/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFormationsIndexRoute =
  AuthenticatedAdminFormationsIndexRouteImport.update({
    id: '/formations/',
    path: '/formations/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFormationsIdRoute =
  AuthenticatedAdminFormationsIdRouteImport.update({
    id: '/formations/$id',
    path: '/formations/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedExamensIdPassageRoute =
  AuthenticatedExamensIdPassageRouteImport.update({
    id: '/examens/$id/passage',
    path: '/examens/$id/passage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/api/auth/discord/callback',
  path: '/api/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordOnboardingRoute =
  ApiAuthDiscordOnboardingRouteImport.update({
    id: '/api/auth/discord/onboarding',
    path: '/api/auth/discord/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDiscordStartRoute = ApiAuthDiscordStartRouteImport.update({
  id: '/api/auth/discord/start',
  path: '/api/auth/discord/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExamensIdResultatAttemptIdRoute =
  AuthenticatedExamensIdResultatAttemptIdRouteImport.update({
    id: '/examens/$id/resultat/$attemptId',
    path: '/examens/$id/resultat/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExamensIdCopiesAttemptIdRoute =
  AuthenticatedAdminExamensIdCopiesAttemptIdRouteImport.update({
    id: '/copies/$attemptId',
    path: '/copies/$attemptId',
    getParentRoute: () => AuthenticatedAdminExamensIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/admissions': typeof AdmissionsRoute
  '/assurances': typeof AssurancesRoute
  '/auth': typeof AuthRoute
  '/avocats': typeof AvocatsRouteWithChildren
  '/bibliotheque': typeof BibliothequeRoute
  '/cabinet': typeof CabinetRoute
  '/cabinets': typeof CabinetsRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/discipline': typeof DisciplineRoute
  '/espace-avocat': typeof EspaceAvocatRoute
  '/espace-batonnier': typeof EspaceBatonnierRoute
  '/examen': typeof ExamenRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/investment': typeof InvestmentRoute
  '/le-barreau': typeof LeBarreauRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/portail-client': typeof PortailClientRouteWithChildren
  '/portail-client-inscription': typeof PortailClientInscriptionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signalement': typeof SignalementRoute
  '/verification': typeof VerificationRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/examinateur': typeof AuthenticatedExaminateurRoute
  '/formateur': typeof AuthenticatedFormateurRoute
  '/mes-dossiers-disciplinaires': typeof AuthenticatedMesDossiersDisciplinairesRoute
  '/messagerie': typeof AuthenticatedMessagerieRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/api/db': typeof ApiDbRoute
  '/api/health': typeof ApiHealthRoute
  '/avocats/$id': typeof AvocatsIdRoute
  '/portail-client/auth': typeof PortailClientAuthRoute
  '/portail-client/documents': typeof PortailClientDocumentsRoute
  '/portail-client/dossiers': typeof PortailClientDossiersRouteWithChildren
  '/portail-client/messages': typeof PortailClientMessagesRoute
  '/portail-client/notifications': typeof PortailClientNotificationsRoute
  '/portail-client/signatures': typeof PortailClientSignaturesRoute
  '/signature/$token': typeof SignatureTokenRoute
  '/portail-client/': typeof PortailClientIndexRoute
  '/admin/actualites': typeof AuthenticatedAdminActualitesRoute
  '/admin/avocats': typeof AuthenticatedAdminAvocatsRoute
  '/admin/bibliotheque': typeof AuthenticatedAdminBibliothequeRoute
  '/admin/cabinets': typeof AuthenticatedAdminCabinetsRoute
  '/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/discipline': typeof AuthenticatedAdminDisciplineRouteWithChildren
  '/admin/enterprises': typeof AuthenticatedAdminEnterprisesRouteWithChildren
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/sauvegardes': typeof AuthenticatedAdminSauvegardesRoute
  '/cabinet/dossiers': typeof AuthenticatedCabinetDossiersRoute
  '/cabinet/facturation': typeof AuthenticatedCabinetFacturationRoute
  '/cabinet/formations': typeof AuthenticatedCabinetFormationsRoute
  '/cabinet/membres': typeof AuthenticatedCabinetMembresRoute
  '/cabinet/modeles': typeof AuthenticatedCabinetModelesRoute
  '/cabinet/parametres': typeof AuthenticatedCabinetParametresRoute
  '/cabinet/tarifs': typeof AuthenticatedCabinetTarifsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/dossiers/$matterId': typeof AuthenticatedDossiersMatterIdRoute
  '/facturation/$id': typeof AuthenticatedFacturationIdRoute
  '/formations/$slug': typeof AuthenticatedFormationsSlugRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/storage/object': typeof ApiStorageObjectRoute
  '/api/storage/op': typeof ApiStorageOpRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/portail-client/dossiers/$matterId': typeof PortailClientDossiersMatterIdRoute
  '/verification/facture/$token': typeof VerificationFactureTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cabinet/': typeof AuthenticatedCabinetIndexRoute
  '/dossiers/': typeof AuthenticatedDossiersIndexRoute
  '/examens/': typeof AuthenticatedExamensIndexRoute
  '/facturation/': typeof AuthenticatedFacturationIndexRoute
  '/admin/discipline/$caseId': typeof AuthenticatedAdminDisciplineCaseIdRoute
  '/admin/enterprises/$firmId': typeof AuthenticatedAdminEnterprisesFirmIdRoute
  '/admin/examens/$id': typeof AuthenticatedAdminExamensIdRouteWithChildren
  '/admin/formations/$id': typeof AuthenticatedAdminFormationsIdRoute
  '/examens/$id/passage': typeof AuthenticatedExamensIdPassageRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/onboarding': typeof ApiAuthDiscordOnboardingRoute
  '/api/auth/discord/start': typeof ApiAuthDiscordStartRoute
  '/admin/examens/': typeof AuthenticatedAdminExamensIndexRoute
  '/admin/formations/': typeof AuthenticatedAdminFormationsIndexRoute
  '/examens/$id/resultat/$attemptId': typeof AuthenticatedExamensIdResultatAttemptIdRoute
  '/admin/examens/$id/copies/$attemptId': typeof AuthenticatedAdminExamensIdCopiesAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/admissions': typeof AdmissionsRoute
  '/assurances': typeof AssurancesRoute
  '/auth': typeof AuthRoute
  '/avocats': typeof AvocatsRouteWithChildren
  '/bibliotheque': typeof BibliothequeRoute
  '/cabinet': typeof AuthenticatedCabinetIndexRoute
  '/cabinets': typeof CabinetsRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/discipline': typeof DisciplineRoute
  '/espace-avocat': typeof EspaceAvocatRoute
  '/espace-batonnier': typeof EspaceBatonnierRoute
  '/examen': typeof ExamenRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/investment': typeof InvestmentRoute
  '/le-barreau': typeof LeBarreauRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/portail-client-inscription': typeof PortailClientInscriptionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signalement': typeof SignalementRoute
  '/verification': typeof VerificationRouteWithChildren
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/examinateur': typeof AuthenticatedExaminateurRoute
  '/formateur': typeof AuthenticatedFormateurRoute
  '/mes-dossiers-disciplinaires': typeof AuthenticatedMesDossiersDisciplinairesRoute
  '/messagerie': typeof AuthenticatedMessagerieRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/api/db': typeof ApiDbRoute
  '/api/health': typeof ApiHealthRoute
  '/avocats/$id': typeof AvocatsIdRoute
  '/portail-client/auth': typeof PortailClientAuthRoute
  '/portail-client/documents': typeof PortailClientDocumentsRoute
  '/portail-client/dossiers': typeof PortailClientDossiersRouteWithChildren
  '/portail-client/messages': typeof PortailClientMessagesRoute
  '/portail-client/notifications': typeof PortailClientNotificationsRoute
  '/portail-client/signatures': typeof PortailClientSignaturesRoute
  '/signature/$token': typeof SignatureTokenRoute
  '/portail-client': typeof PortailClientIndexRoute
  '/admin/actualites': typeof AuthenticatedAdminActualitesRoute
  '/admin/avocats': typeof AuthenticatedAdminAvocatsRoute
  '/admin/bibliotheque': typeof AuthenticatedAdminBibliothequeRoute
  '/admin/cabinets': typeof AuthenticatedAdminCabinetsRoute
  '/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/discipline': typeof AuthenticatedAdminDisciplineRouteWithChildren
  '/admin/enterprises': typeof AuthenticatedAdminEnterprisesRouteWithChildren
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/sauvegardes': typeof AuthenticatedAdminSauvegardesRoute
  '/cabinet/dossiers': typeof AuthenticatedCabinetDossiersRoute
  '/cabinet/facturation': typeof AuthenticatedCabinetFacturationRoute
  '/cabinet/formations': typeof AuthenticatedCabinetFormationsRoute
  '/cabinet/membres': typeof AuthenticatedCabinetMembresRoute
  '/cabinet/modeles': typeof AuthenticatedCabinetModelesRoute
  '/cabinet/parametres': typeof AuthenticatedCabinetParametresRoute
  '/cabinet/tarifs': typeof AuthenticatedCabinetTarifsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/dossiers/$matterId': typeof AuthenticatedDossiersMatterIdRoute
  '/facturation/$id': typeof AuthenticatedFacturationIdRoute
  '/formations/$slug': typeof AuthenticatedFormationsSlugRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/storage/object': typeof ApiStorageObjectRoute
  '/api/storage/op': typeof ApiStorageOpRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/portail-client/dossiers/$matterId': typeof PortailClientDossiersMatterIdRoute
  '/verification/facture/$token': typeof VerificationFactureTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dossiers': typeof AuthenticatedDossiersIndexRoute
  '/examens': typeof AuthenticatedExamensIndexRoute
  '/facturation': typeof AuthenticatedFacturationIndexRoute
  '/admin/discipline/$caseId': typeof AuthenticatedAdminDisciplineCaseIdRoute
  '/admin/enterprises/$firmId': typeof AuthenticatedAdminEnterprisesFirmIdRoute
  '/admin/examens/$id': typeof AuthenticatedAdminExamensIdRouteWithChildren
  '/admin/formations/$id': typeof AuthenticatedAdminFormationsIdRoute
  '/examens/$id/passage': typeof AuthenticatedExamensIdPassageRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/onboarding': typeof ApiAuthDiscordOnboardingRoute
  '/api/auth/discord/start': typeof ApiAuthDiscordStartRoute
  '/admin/examens': typeof AuthenticatedAdminExamensIndexRoute
  '/admin/formations': typeof AuthenticatedAdminFormationsIndexRoute
  '/examens/$id/resultat/$attemptId': typeof AuthenticatedExamensIdResultatAttemptIdRoute
  '/admin/examens/$id/copies/$attemptId': typeof AuthenticatedAdminExamensIdCopiesAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/actualites': typeof ActualitesRoute
  '/admissions': typeof AdmissionsRoute
  '/assurances': typeof AssurancesRoute
  '/auth': typeof AuthRoute
  '/avocats': typeof AvocatsRouteWithChildren
  '/bibliotheque': typeof BibliothequeRoute
  '/cabinet': typeof CabinetRoute
  '/cabinets': typeof CabinetsRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/discipline': typeof DisciplineRoute
  '/espace-avocat': typeof EspaceAvocatRoute
  '/espace-batonnier': typeof EspaceBatonnierRoute
  '/examen': typeof ExamenRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/investment': typeof InvestmentRoute
  '/le-barreau': typeof LeBarreauRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/portail-client': typeof PortailClientRouteWithChildren
  '/portail-client-inscription': typeof PortailClientInscriptionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signalement': typeof SignalementRoute
  '/verification': typeof VerificationRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/examinateur': typeof AuthenticatedExaminateurRoute
  '/_authenticated/formateur': typeof AuthenticatedFormateurRoute
  '/_authenticated/mes-dossiers-disciplinaires': typeof AuthenticatedMesDossiersDisciplinairesRoute
  '/_authenticated/messagerie': typeof AuthenticatedMessagerieRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/taches': typeof AuthenticatedTachesRoute
  '/api/db': typeof ApiDbRoute
  '/api/health': typeof ApiHealthRoute
  '/avocats/$id': typeof AvocatsIdRoute
  '/portail-client/auth': typeof PortailClientAuthRoute
  '/portail-client/documents': typeof PortailClientDocumentsRoute
  '/portail-client/dossiers': typeof PortailClientDossiersRouteWithChildren
  '/portail-client/messages': typeof PortailClientMessagesRoute
  '/portail-client/notifications': typeof PortailClientNotificationsRoute
  '/portail-client/signatures': typeof PortailClientSignaturesRoute
  '/signature/$token': typeof SignatureTokenRoute
  '/portail-client/': typeof PortailClientIndexRoute
  '/_authenticated/admin/actualites': typeof AuthenticatedAdminActualitesRoute
  '/_authenticated/admin/avocats': typeof AuthenticatedAdminAvocatsRoute
  '/_authenticated/admin/bibliotheque': typeof AuthenticatedAdminBibliothequeRoute
  '/_authenticated/admin/cabinets': typeof AuthenticatedAdminCabinetsRoute
  '/_authenticated/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/_authenticated/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/_authenticated/admin/discipline': typeof AuthenticatedAdminDisciplineRouteWithChildren
  '/_authenticated/admin/enterprises': typeof AuthenticatedAdminEnterprisesRouteWithChildren
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/sauvegardes': typeof AuthenticatedAdminSauvegardesRoute
  '/_authenticated/cabinet/dossiers': typeof AuthenticatedCabinetDossiersRoute
  '/_authenticated/cabinet/facturation': typeof AuthenticatedCabinetFacturationRoute
  '/_authenticated/cabinet/formations': typeof AuthenticatedCabinetFormationsRoute
  '/_authenticated/cabinet/membres': typeof AuthenticatedCabinetMembresRoute
  '/_authenticated/cabinet/modeles': typeof AuthenticatedCabinetModelesRoute
  '/_authenticated/cabinet/parametres': typeof AuthenticatedCabinetParametresRoute
  '/_authenticated/cabinet/tarifs': typeof AuthenticatedCabinetTarifsRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/dossiers/$matterId': typeof AuthenticatedDossiersMatterIdRoute
  '/_authenticated/facturation/$id': typeof AuthenticatedFacturationIdRoute
  '/_authenticated/formations/$slug': typeof AuthenticatedFormationsSlugRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/storage/object': typeof ApiStorageObjectRoute
  '/api/storage/op': typeof ApiStorageOpRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/portail-client/dossiers/$matterId': typeof PortailClientDossiersMatterIdRoute
  '/verification/facture/$token': typeof VerificationFactureTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cabinet/': typeof AuthenticatedCabinetIndexRoute
  '/_authenticated/dossiers/': typeof AuthenticatedDossiersIndexRoute
  '/_authenticated/examens/': typeof AuthenticatedExamensIndexRoute
  '/_authenticated/facturation/': typeof AuthenticatedFacturationIndexRoute
  '/_authenticated/admin/discipline/$caseId': typeof AuthenticatedAdminDisciplineCaseIdRoute
  '/_authenticated/admin/enterprises/$firmId': typeof AuthenticatedAdminEnterprisesFirmIdRoute
  '/_authenticated/admin/examens/$id': typeof AuthenticatedAdminExamensIdRouteWithChildren
  '/_authenticated/admin/formations/$id': typeof AuthenticatedAdminFormationsIdRoute
  '/_authenticated/examens/$id/passage': typeof AuthenticatedExamensIdPassageRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/onboarding': typeof ApiAuthDiscordOnboardingRoute
  '/api/auth/discord/start': typeof ApiAuthDiscordStartRoute
  '/_authenticated/admin/examens/': typeof AuthenticatedAdminExamensIndexRoute
  '/_authenticated/admin/formations/': typeof AuthenticatedAdminFormationsIndexRoute
  '/_authenticated/examens/$id/resultat/$attemptId': typeof AuthenticatedExamensIdResultatAttemptIdRoute
  '/_authenticated/admin/examens/$id/copies/$attemptId': typeof AuthenticatedAdminExamensIdCopiesAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/admissions'
    | '/assurances'
    | '/auth'
    | '/avocats'
    | '/bibliotheque'
    | '/cabinet'
    | '/cabinets'
    | '/cgu'
    | '/connexion'
    | '/contact'
    | '/discipline'
    | '/espace-avocat'
    | '/espace-batonnier'
    | '/examen'
    | '/formations'
    | '/inscription'
    | '/investment'
    | '/le-barreau'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/portail-client'
    | '/portail-client-inscription'
    | '/reset-password'
    | '/services'
    | '/signalement'
    | '/verification'
    | '/admin'
    | '/clients'
    | '/examinateur'
    | '/formateur'
    | '/mes-dossiers-disciplinaires'
    | '/messagerie'
    | '/tableau-de-bord'
    | '/taches'
    | '/api/db'
    | '/api/health'
    | '/avocats/$id'
    | '/portail-client/auth'
    | '/portail-client/documents'
    | '/portail-client/dossiers'
    | '/portail-client/messages'
    | '/portail-client/notifications'
    | '/portail-client/signatures'
    | '/signature/$token'
    | '/portail-client/'
    | '/admin/actualites'
    | '/admin/avocats'
    | '/admin/bibliotheque'
    | '/admin/cabinets'
    | '/admin/contenus'
    | '/admin/demandes'
    | '/admin/discipline'
    | '/admin/enterprises'
    | '/admin/journal'
    | '/admin/roles'
    | '/admin/sauvegardes'
    | '/cabinet/dossiers'
    | '/cabinet/facturation'
    | '/cabinet/formations'
    | '/cabinet/membres'
    | '/cabinet/modeles'
    | '/cabinet/parametres'
    | '/cabinet/tarifs'
    | '/clients/$id'
    | '/dossiers/$matterId'
    | '/facturation/$id'
    | '/formations/$slug'
    | '/api/auth/$action'
    | '/api/storage/object'
    | '/api/storage/op'
    | '/api/storage/upload'
    | '/portail-client/dossiers/$matterId'
    | '/verification/facture/$token'
    | '/admin/'
    | '/cabinet/'
    | '/dossiers/'
    | '/examens/'
    | '/facturation/'
    | '/admin/discipline/$caseId'
    | '/admin/enterprises/$firmId'
    | '/admin/examens/$id'
    | '/admin/formations/$id'
    | '/examens/$id/passage'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/onboarding'
    | '/api/auth/discord/start'
    | '/admin/examens/'
    | '/admin/formations/'
    | '/examens/$id/resultat/$attemptId'
    | '/admin/examens/$id/copies/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/admissions'
    | '/assurances'
    | '/auth'
    | '/avocats'
    | '/bibliotheque'
    | '/cabinet'
    | '/cabinets'
    | '/cgu'
    | '/connexion'
    | '/contact'
    | '/discipline'
    | '/espace-avocat'
    | '/espace-batonnier'
    | '/examen'
    | '/formations'
    | '/inscription'
    | '/investment'
    | '/le-barreau'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/portail-client-inscription'
    | '/reset-password'
    | '/services'
    | '/signalement'
    | '/verification'
    | '/clients'
    | '/examinateur'
    | '/formateur'
    | '/mes-dossiers-disciplinaires'
    | '/messagerie'
    | '/tableau-de-bord'
    | '/taches'
    | '/api/db'
    | '/api/health'
    | '/avocats/$id'
    | '/portail-client/auth'
    | '/portail-client/documents'
    | '/portail-client/dossiers'
    | '/portail-client/messages'
    | '/portail-client/notifications'
    | '/portail-client/signatures'
    | '/signature/$token'
    | '/portail-client'
    | '/admin/actualites'
    | '/admin/avocats'
    | '/admin/bibliotheque'
    | '/admin/cabinets'
    | '/admin/contenus'
    | '/admin/demandes'
    | '/admin/discipline'
    | '/admin/enterprises'
    | '/admin/journal'
    | '/admin/roles'
    | '/admin/sauvegardes'
    | '/cabinet/dossiers'
    | '/cabinet/facturation'
    | '/cabinet/formations'
    | '/cabinet/membres'
    | '/cabinet/modeles'
    | '/cabinet/parametres'
    | '/cabinet/tarifs'
    | '/clients/$id'
    | '/dossiers/$matterId'
    | '/facturation/$id'
    | '/formations/$slug'
    | '/api/auth/$action'
    | '/api/storage/object'
    | '/api/storage/op'
    | '/api/storage/upload'
    | '/portail-client/dossiers/$matterId'
    | '/verification/facture/$token'
    | '/admin'
    | '/dossiers'
    | '/examens'
    | '/facturation'
    | '/admin/discipline/$caseId'
    | '/admin/enterprises/$firmId'
    | '/admin/examens/$id'
    | '/admin/formations/$id'
    | '/examens/$id/passage'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/onboarding'
    | '/api/auth/discord/start'
    | '/admin/examens'
    | '/admin/formations'
    | '/examens/$id/resultat/$attemptId'
    | '/admin/examens/$id/copies/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/actualites'
    | '/admissions'
    | '/assurances'
    | '/auth'
    | '/avocats'
    | '/bibliotheque'
    | '/cabinet'
    | '/cabinets'
    | '/cgu'
    | '/connexion'
    | '/contact'
    | '/discipline'
    | '/espace-avocat'
    | '/espace-batonnier'
    | '/examen'
    | '/formations'
    | '/inscription'
    | '/investment'
    | '/le-barreau'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/portail-client'
    | '/portail-client-inscription'
    | '/reset-password'
    | '/services'
    | '/signalement'
    | '/verification'
    | '/_authenticated/admin'
    | '/_authenticated/clients'
    | '/_authenticated/examinateur'
    | '/_authenticated/formateur'
    | '/_authenticated/mes-dossiers-disciplinaires'
    | '/_authenticated/messagerie'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/taches'
    | '/api/db'
    | '/api/health'
    | '/avocats/$id'
    | '/portail-client/auth'
    | '/portail-client/documents'
    | '/portail-client/dossiers'
    | '/portail-client/messages'
    | '/portail-client/notifications'
    | '/portail-client/signatures'
    | '/signature/$token'
    | '/portail-client/'
    | '/_authenticated/admin/actualites'
    | '/_authenticated/admin/avocats'
    | '/_authenticated/admin/bibliotheque'
    | '/_authenticated/admin/cabinets'
    | '/_authenticated/admin/contenus'
    | '/_authenticated/admin/demandes'
    | '/_authenticated/admin/discipline'
    | '/_authenticated/admin/enterprises'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/sauvegardes'
    | '/_authenticated/cabinet/dossiers'
    | '/_authenticated/cabinet/facturation'
    | '/_authenticated/cabinet/formations'
    | '/_authenticated/cabinet/membres'
    | '/_authenticated/cabinet/modeles'
    | '/_authenticated/cabinet/parametres'
    | '/_authenticated/cabinet/tarifs'
    | '/_authenticated/clients/$id'
    | '/_authenticated/dossiers/$matterId'
    | '/_authenticated/facturation/$id'
    | '/_authenticated/formations/$slug'
    | '/api/auth/$action'
    | '/api/storage/object'
    | '/api/storage/op'
    | '/api/storage/upload'
    | '/portail-client/dossiers/$matterId'
    | '/verification/facture/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/cabinet/'
    | '/_authenticated/dossiers/'
    | '/_authenticated/examens/'
    | '/_authenticated/facturation/'
    | '/_authenticated/admin/discipline/$caseId'
    | '/_authenticated/admin/enterprises/$firmId'
    | '/_authenticated/admin/examens/$id'
    | '/_authenticated/admin/formations/$id'
    | '/_authenticated/examens/$id/passage'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/onboarding'
    | '/api/auth/discord/start'
    | '/_authenticated/admin/examens/'
    | '/_authenticated/admin/formations/'
    | '/_authenticated/examens/$id/resultat/$attemptId'
    | '/_authenticated/admin/examens/$id/copies/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActualitesRoute: typeof ActualitesRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AssurancesRoute: typeof AssurancesRoute
  AuthRoute: typeof AuthRoute
  AvocatsRoute: typeof AvocatsRouteWithChildren
  BibliothequeRoute: typeof BibliothequeRoute
  CabinetRoute: typeof CabinetRoute
  CabinetsRoute: typeof CabinetsRoute
  CguRoute: typeof CguRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DisciplineRoute: typeof DisciplineRoute
  EspaceAvocatRoute: typeof EspaceAvocatRoute
  EspaceBatonnierRoute: typeof EspaceBatonnierRoute
  ExamenRoute: typeof ExamenRoute
  FormationsRoute: typeof FormationsRoute
  InscriptionRoute: typeof InscriptionRoute
  InvestmentRoute: typeof InvestmentRoute
  LeBarreauRoute: typeof LeBarreauRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PortailClientRoute: typeof PortailClientRouteWithChildren
  PortailClientInscriptionRoute: typeof PortailClientInscriptionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SignalementRoute: typeof SignalementRoute
  VerificationRoute: typeof VerificationRouteWithChildren
  ApiDbRoute: typeof ApiDbRoute
  ApiHealthRoute: typeof ApiHealthRoute
  SignatureTokenRoute: typeof SignatureTokenRoute
  ApiAuthActionRoute: typeof ApiAuthActionRoute
  ApiStorageObjectRoute: typeof ApiStorageObjectRoute
  ApiStorageOpRoute: typeof ApiStorageOpRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
  ApiAuthDiscordOnboardingRoute: typeof ApiAuthDiscordOnboardingRoute
  ApiAuthDiscordStartRoute: typeof ApiAuthDiscordStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurances': {
      id: '/assurances'
      path: '/assurances'
      fullPath: '/assurances'
      preLoaderRoute: typeof AssurancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avocats': {
      id: '/avocats'
      path: '/avocats'
      fullPath: '/avocats'
      preLoaderRoute: typeof AvocatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinets': {
      id: '/cabinets'
      path: '/cabinets'
      fullPath: '/cabinets'
      preLoaderRoute: typeof CabinetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline': {
      id: '/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-avocat': {
      id: '/espace-avocat'
      path: '/espace-avocat'
      fullPath: '/espace-avocat'
      preLoaderRoute: typeof EspaceAvocatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-batonnier': {
      id: '/espace-batonnier'
      path: '/espace-batonnier'
      fullPath: '/espace-batonnier'
      preLoaderRoute: typeof EspaceBatonnierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examen': {
      id: '/examen'
      path: '/examen'
      fullPath: '/examen'
      preLoaderRoute: typeof ExamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-barreau': {
      id: '/le-barreau'
      path: '/le-barreau'
      fullPath: '/le-barreau'
      preLoaderRoute: typeof LeBarreauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail-client': {
      id: '/portail-client'
      path: '/portail-client'
      fullPath: '/portail-client'
      preLoaderRoute: typeof PortailClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail-client-inscription': {
      id: '/portail-client-inscription'
      path: '/portail-client-inscription'
      fullPath: '/portail-client-inscription'
      preLoaderRoute: typeof PortailClientInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signalement': {
      id: '/signalement'
      path: '/signalement'
      fullPath: '/signalement'
      preLoaderRoute: typeof SignalementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinateur': {
      id: '/_authenticated/examinateur'
      path: '/examinateur'
      fullPath: '/examinateur'
      preLoaderRoute: typeof AuthenticatedExaminateurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formateur': {
      id: '/_authenticated/formateur'
      path: '/formateur'
      fullPath: '/formateur'
      preLoaderRoute: typeof AuthenticatedFormateurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-dossiers-disciplinaires': {
      id: '/_authenticated/mes-dossiers-disciplinaires'
      path: '/mes-dossiers-disciplinaires'
      fullPath: '/mes-dossiers-disciplinaires'
      preLoaderRoute: typeof AuthenticatedMesDossiersDisciplinairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messagerie': {
      id: '/_authenticated/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof AuthenticatedMessagerieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taches': {
      id: '/_authenticated/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof AuthenticatedTachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/db': {
      id: '/api/db'
      path: '/api/db'
      fullPath: '/api/db'
      preLoaderRoute: typeof ApiDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avocats/$id': {
      id: '/avocats/$id'
      path: '/$id'
      fullPath: '/avocats/$id'
      preLoaderRoute: typeof AvocatsIdRouteImport
      parentRoute: typeof AvocatsRoute
    }
    '/portail-client/': {
      id: '/portail-client/'
      path: '/'
      fullPath: '/portail-client/'
      preLoaderRoute: typeof PortailClientIndexRouteImport
      parentRoute: typeof PortailClientRoute
    }
    '/portail-client/auth': {
      id: '/portail-client/auth'
      path: '/auth'
      fullPath: '/portail-client/auth'
      preLoaderRoute: typeof PortailClientAuthRouteImport
      parentRoute: typeof PortailClientRoute
    }
    '/portail-client/documents': {
      id: '/portail-client/documents'
      path: '/documents'
      fullPath: '/portail-client/documents'
      preLoaderRoute: typeof PortailClientDocumentsRouteImport
      parentRoute: typeof PortailClientRoute
    }
    '/portail-client/dossiers': {
      id: '/portail-client/dossiers'
      path: '/dossiers'
      fullPath: '/portail-client/dossiers'
      preLoaderRoute: typeof PortailClientDossiersRouteImport
      parentRoute: typeof PortailClientRoute
    }
    '/portail-client/messages': {
      id: '/portail-client/messages'
      path: '/messages'
      fullPath: '/portail-client/messages'
      preLoaderRoute: typeof PortailClientMessagesRouteImport
      parentRoute: typeof PortailClientRoute
    }
    '/portail-client/notifications': {
      id: '/portail-client/notifications'
      path: '/notifications'
      fullPath: '/portail-client/notifications'
      preLoaderRoute: typeof PortailClientNotificationsRouteImport
      parentRoute: typeof PortailClientRoute
    }
    '/portail-client/signatures': {
      id: '/portail-client/signatures'
      path: '/signatures'
      fullPath: '/portail-client/signatures'
      preLoaderRoute: typeof PortailClientSignaturesRouteImport
      parentRoute: typeof PortailClientRoute
    }
    '/signature/$token': {
      id: '/signature/$token'
      path: '/signature/$token'
      fullPath: '/signature/$token'
      preLoaderRoute: typeof SignatureTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/actualites': {
      id: '/_authenticated/admin/actualites'
      path: '/actualites'
      fullPath: '/admin/actualites'
      preLoaderRoute: typeof AuthenticatedAdminActualitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/avocats': {
      id: '/_authenticated/admin/avocats'
      path: '/avocats'
      fullPath: '/admin/avocats'
      preLoaderRoute: typeof AuthenticatedAdminAvocatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bibliotheque': {
      id: '/_authenticated/admin/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/admin/bibliotheque'
      preLoaderRoute: typeof AuthenticatedAdminBibliothequeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cabinets': {
      id: '/_authenticated/admin/cabinets'
      path: '/cabinets'
      fullPath: '/admin/cabinets'
      preLoaderRoute: typeof AuthenticatedAdminCabinetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contenus': {
      id: '/_authenticated/admin/contenus'
      path: '/contenus'
      fullPath: '/admin/contenus'
      preLoaderRoute: typeof AuthenticatedAdminContenusRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/demandes': {
      id: '/_authenticated/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AuthenticatedAdminDemandesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/discipline': {
      id: '/_authenticated/admin/discipline'
      path: '/discipline'
      fullPath: '/admin/discipline'
      preLoaderRoute: typeof AuthenticatedAdminDisciplineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enterprises': {
      id: '/_authenticated/admin/enterprises'
      path: '/enterprises'
      fullPath: '/admin/enterprises'
      preLoaderRoute: typeof AuthenticatedAdminEnterprisesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sauvegardes': {
      id: '/_authenticated/admin/sauvegardes'
      path: '/sauvegardes'
      fullPath: '/admin/sauvegardes'
      preLoaderRoute: typeof AuthenticatedAdminSauvegardesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/cabinet/': {
      id: '/_authenticated/cabinet/'
      path: '/cabinet'
      fullPath: '/cabinet/'
      preLoaderRoute: typeof AuthenticatedCabinetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/dossiers': {
      id: '/_authenticated/cabinet/dossiers'
      path: '/cabinet/dossiers'
      fullPath: '/cabinet/dossiers'
      preLoaderRoute: typeof AuthenticatedCabinetDossiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/facturation': {
      id: '/_authenticated/cabinet/facturation'
      path: '/cabinet/facturation'
      fullPath: '/cabinet/facturation'
      preLoaderRoute: typeof AuthenticatedCabinetFacturationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/formations': {
      id: '/_authenticated/cabinet/formations'
      path: '/cabinet/formations'
      fullPath: '/cabinet/formations'
      preLoaderRoute: typeof AuthenticatedCabinetFormationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/membres': {
      id: '/_authenticated/cabinet/membres'
      path: '/cabinet/membres'
      fullPath: '/cabinet/membres'
      preLoaderRoute: typeof AuthenticatedCabinetMembresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/modeles': {
      id: '/_authenticated/cabinet/modeles'
      path: '/cabinet/modeles'
      fullPath: '/cabinet/modeles'
      preLoaderRoute: typeof AuthenticatedCabinetModelesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/parametres': {
      id: '/_authenticated/cabinet/parametres'
      path: '/cabinet/parametres'
      fullPath: '/cabinet/parametres'
      preLoaderRoute: typeof AuthenticatedCabinetParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/tarifs': {
      id: '/_authenticated/cabinet/tarifs'
      path: '/cabinet/tarifs'
      fullPath: '/cabinet/tarifs'
      preLoaderRoute: typeof AuthenticatedCabinetTarifsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/dossiers/': {
      id: '/_authenticated/dossiers/'
      path: '/dossiers'
      fullPath: '/dossiers/'
      preLoaderRoute: typeof AuthenticatedDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/$matterId': {
      id: '/_authenticated/dossiers/$matterId'
      path: '/dossiers/$matterId'
      fullPath: '/dossiers/$matterId'
      preLoaderRoute: typeof AuthenticatedDossiersMatterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examens/': {
      id: '/_authenticated/examens/'
      path: '/examens'
      fullPath: '/examens/'
      preLoaderRoute: typeof AuthenticatedExamensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturation/': {
      id: '/_authenticated/facturation/'
      path: '/facturation'
      fullPath: '/facturation/'
      preLoaderRoute: typeof AuthenticatedFacturationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturation/$id': {
      id: '/_authenticated/facturation/$id'
      path: '/facturation/$id'
      fullPath: '/facturation/$id'
      preLoaderRoute: typeof AuthenticatedFacturationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formations/$slug': {
      id: '/_authenticated/formations/$slug'
      path: '/formations/$slug'
      fullPath: '/formations/$slug'
      preLoaderRoute: typeof AuthenticatedFormationsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$action': {
      id: '/api/auth/$action'
      path: '/api/auth/$action'
      fullPath: '/api/auth/$action'
      preLoaderRoute: typeof ApiAuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/object': {
      id: '/api/storage/object'
      path: '/api/storage/object'
      fullPath: '/api/storage/object'
      preLoaderRoute: typeof ApiStorageObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/op': {
      id: '/api/storage/op'
      path: '/api/storage/op'
      fullPath: '/api/storage/op'
      preLoaderRoute: typeof ApiStorageOpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail-client/dossiers/$matterId': {
      id: '/portail-client/dossiers/$matterId'
      path: '/$matterId'
      fullPath: '/portail-client/dossiers/$matterId'
      preLoaderRoute: typeof PortailClientDossiersMatterIdRouteImport
      parentRoute: typeof PortailClientDossiersRoute
    }
    '/verification/facture/$token': {
      id: '/verification/facture/$token'
      path: '/facture/$token'
      fullPath: '/verification/facture/$token'
      preLoaderRoute: typeof VerificationFactureTokenRouteImport
      parentRoute: typeof VerificationRoute
    }
    '/_authenticated/admin/discipline/$caseId': {
      id: '/_authenticated/admin/discipline/$caseId'
      path: '/$caseId'
      fullPath: '/admin/discipline/$caseId'
      preLoaderRoute: typeof AuthenticatedAdminDisciplineCaseIdRouteImport
      parentRoute: typeof AuthenticatedAdminDisciplineRoute
    }
    '/_authenticated/admin/enterprises/$firmId': {
      id: '/_authenticated/admin/enterprises/$firmId'
      path: '/$firmId'
      fullPath: '/admin/enterprises/$firmId'
      preLoaderRoute: typeof AuthenticatedAdminEnterprisesFirmIdRouteImport
      parentRoute: typeof AuthenticatedAdminEnterprisesRoute
    }
    '/_authenticated/admin/examens/': {
      id: '/_authenticated/admin/examens/'
      path: '/examens'
      fullPath: '/admin/examens/'
      preLoaderRoute: typeof AuthenticatedAdminExamensIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/examens/$id': {
      id: '/_authenticated/admin/examens/$id'
      path: '/examens/$id'
      fullPath: '/admin/examens/$id'
      preLoaderRoute: typeof AuthenticatedAdminExamensIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/formations/': {
      id: '/_authenticated/admin/formations/'
      path: '/formations'
      fullPath: '/admin/formations/'
      preLoaderRoute: typeof AuthenticatedAdminFormationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/formations/$id': {
      id: '/_authenticated/admin/formations/$id'
      path: '/formations/$id'
      fullPath: '/admin/formations/$id'
      preLoaderRoute: typeof AuthenticatedAdminFormationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/examens/$id/passage': {
      id: '/_authenticated/examens/$id/passage'
      path: '/examens/$id/passage'
      fullPath: '/examens/$id/passage'
      preLoaderRoute: typeof AuthenticatedExamensIdPassageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/api/auth/discord/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/onboarding': {
      id: '/api/auth/discord/onboarding'
      path: '/api/auth/discord/onboarding'
      fullPath: '/api/auth/discord/onboarding'
      preLoaderRoute: typeof ApiAuthDiscordOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/start': {
      id: '/api/auth/discord/start'
      path: '/api/auth/discord/start'
      fullPath: '/api/auth/discord/start'
      preLoaderRoute: typeof ApiAuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/examens/$id/resultat/$attemptId': {
      id: '/_authenticated/examens/$id/resultat/$attemptId'
      path: '/examens/$id/resultat/$attemptId'
      fullPath: '/examens/$id/resultat/$attemptId'
      preLoaderRoute: typeof AuthenticatedExamensIdResultatAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/examens/$id/copies/$attemptId': {
      id: '/_authenticated/admin/examens/$id/copies/$attemptId'
      path: '/copies/$attemptId'
      fullPath: '/admin/examens/$id/copies/$attemptId'
      preLoaderRoute: typeof AuthenticatedAdminExamensIdCopiesAttemptIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamensIdRoute
    }
  }
}

interface AuthenticatedAdminDisciplineRouteChildren {
  AuthenticatedAdminDisciplineCaseIdRoute: typeof AuthenticatedAdminDisciplineCaseIdRoute
}

const AuthenticatedAdminDisciplineRouteChildren: AuthenticatedAdminDisciplineRouteChildren =
  {
    AuthenticatedAdminDisciplineCaseIdRoute:
      AuthenticatedAdminDisciplineCaseIdRoute,
  }

const AuthenticatedAdminDisciplineRouteWithChildren =
  AuthenticatedAdminDisciplineRoute._addFileChildren(
    AuthenticatedAdminDisciplineRouteChildren,
  )

interface AuthenticatedAdminEnterprisesRouteChildren {
  AuthenticatedAdminEnterprisesFirmIdRoute: typeof AuthenticatedAdminEnterprisesFirmIdRoute
}

const AuthenticatedAdminEnterprisesRouteChildren: AuthenticatedAdminEnterprisesRouteChildren =
  {
    AuthenticatedAdminEnterprisesFirmIdRoute:
      AuthenticatedAdminEnterprisesFirmIdRoute,
  }

const AuthenticatedAdminEnterprisesRouteWithChildren =
  AuthenticatedAdminEnterprisesRoute._addFileChildren(
    AuthenticatedAdminEnterprisesRouteChildren,
  )

interface AuthenticatedAdminExamensIdRouteChildren {
  AuthenticatedAdminExamensIdCopiesAttemptIdRoute: typeof AuthenticatedAdminExamensIdCopiesAttemptIdRoute
}

const AuthenticatedAdminExamensIdRouteChildren: AuthenticatedAdminExamensIdRouteChildren =
  {
    AuthenticatedAdminExamensIdCopiesAttemptIdRoute:
      AuthenticatedAdminExamensIdCopiesAttemptIdRoute,
  }

const AuthenticatedAdminExamensIdRouteWithChildren =
  AuthenticatedAdminExamensIdRoute._addFileChildren(
    AuthenticatedAdminExamensIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActualitesRoute: typeof AuthenticatedAdminActualitesRoute
  AuthenticatedAdminAvocatsRoute: typeof AuthenticatedAdminAvocatsRoute
  AuthenticatedAdminBibliothequeRoute: typeof AuthenticatedAdminBibliothequeRoute
  AuthenticatedAdminCabinetsRoute: typeof AuthenticatedAdminCabinetsRoute
  AuthenticatedAdminContenusRoute: typeof AuthenticatedAdminContenusRoute
  AuthenticatedAdminDemandesRoute: typeof AuthenticatedAdminDemandesRoute
  AuthenticatedAdminDisciplineRoute: typeof AuthenticatedAdminDisciplineRouteWithChildren
  AuthenticatedAdminEnterprisesRoute: typeof AuthenticatedAdminEnterprisesRouteWithChildren
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSauvegardesRoute: typeof AuthenticatedAdminSauvegardesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminExamensIdRoute: typeof AuthenticatedAdminExamensIdRouteWithChildren
  AuthenticatedAdminFormationsIdRoute: typeof AuthenticatedAdminFormationsIdRoute
  AuthenticatedAdminExamensIndexRoute: typeof AuthenticatedAdminExamensIndexRoute
  AuthenticatedAdminFormationsIndexRoute: typeof AuthenticatedAdminFormationsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActualitesRoute: AuthenticatedAdminActualitesRoute,
  AuthenticatedAdminAvocatsRoute: AuthenticatedAdminAvocatsRoute,
  AuthenticatedAdminBibliothequeRoute: AuthenticatedAdminBibliothequeRoute,
  AuthenticatedAdminCabinetsRoute: AuthenticatedAdminCabinetsRoute,
  AuthenticatedAdminContenusRoute: AuthenticatedAdminContenusRoute,
  AuthenticatedAdminDemandesRoute: AuthenticatedAdminDemandesRoute,
  AuthenticatedAdminDisciplineRoute:
    AuthenticatedAdminDisciplineRouteWithChildren,
  AuthenticatedAdminEnterprisesRoute:
    AuthenticatedAdminEnterprisesRouteWithChildren,
  AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSauvegardesRoute: AuthenticatedAdminSauvegardesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminExamensIdRoute:
    AuthenticatedAdminExamensIdRouteWithChildren,
  AuthenticatedAdminFormationsIdRoute: AuthenticatedAdminFormationsIdRoute,
  AuthenticatedAdminExamensIndexRoute: AuthenticatedAdminExamensIndexRoute,
  AuthenticatedAdminFormationsIndexRoute:
    AuthenticatedAdminFormationsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedExaminateurRoute: typeof AuthenticatedExaminateurRoute
  AuthenticatedFormateurRoute: typeof AuthenticatedFormateurRoute
  AuthenticatedMesDossiersDisciplinairesRoute: typeof AuthenticatedMesDossiersDisciplinairesRoute
  AuthenticatedMessagerieRoute: typeof AuthenticatedMessagerieRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedTachesRoute: typeof AuthenticatedTachesRoute
  AuthenticatedCabinetDossiersRoute: typeof AuthenticatedCabinetDossiersRoute
  AuthenticatedCabinetFacturationRoute: typeof AuthenticatedCabinetFacturationRoute
  AuthenticatedCabinetFormationsRoute: typeof AuthenticatedCabinetFormationsRoute
  AuthenticatedCabinetMembresRoute: typeof AuthenticatedCabinetMembresRoute
  AuthenticatedCabinetModelesRoute: typeof AuthenticatedCabinetModelesRoute
  AuthenticatedCabinetParametresRoute: typeof AuthenticatedCabinetParametresRoute
  AuthenticatedCabinetTarifsRoute: typeof AuthenticatedCabinetTarifsRoute
  AuthenticatedDossiersMatterIdRoute: typeof AuthenticatedDossiersMatterIdRoute
  AuthenticatedFacturationIdRoute: typeof AuthenticatedFacturationIdRoute
  AuthenticatedFormationsSlugRoute: typeof AuthenticatedFormationsSlugRoute
  AuthenticatedCabinetIndexRoute: typeof AuthenticatedCabinetIndexRoute
  AuthenticatedDossiersIndexRoute: typeof AuthenticatedDossiersIndexRoute
  AuthenticatedExamensIndexRoute: typeof AuthenticatedExamensIndexRoute
  AuthenticatedFacturationIndexRoute: typeof AuthenticatedFacturationIndexRoute
  AuthenticatedExamensIdPassageRoute: typeof AuthenticatedExamensIdPassageRoute
  AuthenticatedExamensIdResultatAttemptIdRoute: typeof AuthenticatedExamensIdResultatAttemptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedExaminateurRoute: AuthenticatedExaminateurRoute,
  AuthenticatedFormateurRoute: AuthenticatedFormateurRoute,
  AuthenticatedMesDossiersDisciplinairesRoute:
    AuthenticatedMesDossiersDisciplinairesRoute,
  AuthenticatedMessagerieRoute: AuthenticatedMessagerieRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedTachesRoute: AuthenticatedTachesRoute,
  AuthenticatedCabinetDossiersRoute: AuthenticatedCabinetDossiersRoute,
  AuthenticatedCabinetFacturationRoute: AuthenticatedCabinetFacturationRoute,
  AuthenticatedCabinetFormationsRoute: AuthenticatedCabinetFormationsRoute,
  AuthenticatedCabinetMembresRoute: AuthenticatedCabinetMembresRoute,
  AuthenticatedCabinetModelesRoute: AuthenticatedCabinetModelesRoute,
  AuthenticatedCabinetParametresRoute: AuthenticatedCabinetParametresRoute,
  AuthenticatedCabinetTarifsRoute: AuthenticatedCabinetTarifsRoute,
  AuthenticatedDossiersMatterIdRoute: AuthenticatedDossiersMatterIdRoute,
  AuthenticatedFacturationIdRoute: AuthenticatedFacturationIdRoute,
  AuthenticatedFormationsSlugRoute: AuthenticatedFormationsSlugRoute,
  AuthenticatedCabinetIndexRoute: AuthenticatedCabinetIndexRoute,
  AuthenticatedDossiersIndexRoute: AuthenticatedDossiersIndexRoute,
  AuthenticatedExamensIndexRoute: AuthenticatedExamensIndexRoute,
  AuthenticatedFacturationIndexRoute: AuthenticatedFacturationIndexRoute,
  AuthenticatedExamensIdPassageRoute: AuthenticatedExamensIdPassageRoute,
  AuthenticatedExamensIdResultatAttemptIdRoute:
    AuthenticatedExamensIdResultatAttemptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AvocatsRouteChildren {
  AvocatsIdRoute: typeof AvocatsIdRoute
}

const AvocatsRouteChildren: AvocatsRouteChildren = {
  AvocatsIdRoute: AvocatsIdRoute,
}

const AvocatsRouteWithChildren =
  AvocatsRoute._addFileChildren(AvocatsRouteChildren)

interface PortailClientDossiersRouteChildren {
  PortailClientDossiersMatterIdRoute: typeof PortailClientDossiersMatterIdRoute
}

const PortailClientDossiersRouteChildren: PortailClientDossiersRouteChildren = {
  PortailClientDossiersMatterIdRoute: PortailClientDossiersMatterIdRoute,
}

const PortailClientDossiersRouteWithChildren =
  PortailClientDossiersRoute._addFileChildren(
    PortailClientDossiersRouteChildren,
  )

interface PortailClientRouteChildren {
  PortailClientAuthRoute: typeof PortailClientAuthRoute
  PortailClientDocumentsRoute: typeof PortailClientDocumentsRoute
  PortailClientDossiersRoute: typeof PortailClientDossiersRouteWithChildren
  PortailClientMessagesRoute: typeof PortailClientMessagesRoute
  PortailClientNotificationsRoute: typeof PortailClientNotificationsRoute
  PortailClientSignaturesRoute: typeof PortailClientSignaturesRoute
  PortailClientIndexRoute: typeof PortailClientIndexRoute
}

const PortailClientRouteChildren: PortailClientRouteChildren = {
  PortailClientAuthRoute: PortailClientAuthRoute,
  PortailClientDocumentsRoute: PortailClientDocumentsRoute,
  PortailClientDossiersRoute: PortailClientDossiersRouteWithChildren,
  PortailClientMessagesRoute: PortailClientMessagesRoute,
  PortailClientNotificationsRoute: PortailClientNotificationsRoute,
  PortailClientSignaturesRoute: PortailClientSignaturesRoute,
  PortailClientIndexRoute: PortailClientIndexRoute,
}

const PortailClientRouteWithChildren = PortailClientRoute._addFileChildren(
  PortailClientRouteChildren,
)

interface VerificationRouteChildren {
  VerificationFactureTokenRoute: typeof VerificationFactureTokenRoute
}

const VerificationRouteChildren: VerificationRouteChildren = {
  VerificationFactureTokenRoute: VerificationFactureTokenRoute,
}

const VerificationRouteWithChildren = VerificationRoute._addFileChildren(
  VerificationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActualitesRoute: ActualitesRoute,
  AdmissionsRoute: AdmissionsRoute,
  AssurancesRoute: AssurancesRoute,
  AuthRoute: AuthRoute,
  AvocatsRoute: AvocatsRouteWithChildren,
  BibliothequeRoute: BibliothequeRoute,
  CabinetRoute: CabinetRoute,
  CabinetsRoute: CabinetsRoute,
  CguRoute: CguRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DisciplineRoute: DisciplineRoute,
  EspaceAvocatRoute: EspaceAvocatRoute,
  EspaceBatonnierRoute: EspaceBatonnierRoute,
  ExamenRoute: ExamenRoute,
  FormationsRoute: FormationsRoute,
  InscriptionRoute: InscriptionRoute,
  InvestmentRoute: InvestmentRoute,
  LeBarreauRoute: LeBarreauRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PortailClientRoute: PortailClientRouteWithChildren,
  PortailClientInscriptionRoute: PortailClientInscriptionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SignalementRoute: SignalementRoute,
  VerificationRoute: VerificationRouteWithChildren,
  ApiDbRoute: ApiDbRoute,
  ApiHealthRoute: ApiHealthRoute,
  SignatureTokenRoute: SignatureTokenRoute,
  ApiAuthActionRoute: ApiAuthActionRoute,
  ApiStorageObjectRoute: ApiStorageObjectRoute,
  ApiStorageOpRoute: ApiStorageOpRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
  ApiAuthDiscordOnboardingRoute: ApiAuthDiscordOnboardingRoute,
  ApiAuthDiscordStartRoute: ApiAuthDiscordStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
