// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";
import { readActiveFirmId } from "@/lib/enterprise";

export function authenticatedServerFnHeaders(token: string | null, activeFirmId: string | null) {
  return {
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
    ...(activeFirmId ? { "x-enterprise-id": activeFirmId } : {}),
  };
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    return next({
      headers: authenticatedServerFnHeaders(token ?? null, readActiveFirmId()),
    });
  },
);
